In [1]:
import pandas as pd
# import os
import datetime
import matplotlib.pyplot as plt
import numpy as np

In [2]:
test_df = pd.read_csv("../data/test.csv", parse_dates=['release_date'])

In [3]:
test_df.shape

(4398, 22)

In [4]:
del test_df['belongs_to_collection'] # null값이 전체의 80%
del test_df['homepage'] # null값이 전체의 68%
del test_df['runtime'] # corr의 수가 0.239114
test_df = test_df.dropna(axis=0).reset_index()
del test_df['index']

In [5]:
genres_df = pd.DataFrame(test_df['genres'].copy())
production_companies_df = pd.DataFrame(test_df['production_companies'].copy())
production_countries_df = pd.DataFrame(test_df['production_countries'].copy())
spoken_languages_df = pd.DataFrame(test_df['spoken_languages'].copy())
Keywords_df = pd.DataFrame(test_df['Keywords'].copy())
cast_df = pd.DataFrame(test_df['cast'].copy())
crew_df = pd.DataFrame(test_df['crew'].copy())
# revenue_df = pd.DataFrame(test_df['revenue'].copy())

In [6]:
original_language_dummies = pd.get_dummies(test_df['original_language'])[['en','zh','sv','ja']]

test_df = pd.concat([test_df, original_language_dummies],axis=1)

del test_df['original_language']

In [7]:
test_df

,id,budget,genres,imdb_id,original_title,overview,popularity,poster_path,production_companies,production_countries,...,status,tagline,title,Keywords,cast,crew,en,zh,sv,ja
0,3002,88000,"[{'id': 27, 'name': 'Horror'}, {'id': 878, 'na...",tt0051380,Attack of the 50 Foot Woman,When an abused wife grows to giant size becaus...,3.559789,/9MgBNBqlH1sG4yG2u4XkwI5CoJa.jpg,"[{'name': 'Woolner Brothers Pictures Inc.', 'i...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,A titanic beauty spreads a macabre wave of hor...,Attack of the 50 Foot Woman,"[{'id': 9748, 'name': 'revenge'}, {'id': 9951,...","[{'cast_id': 2, 'character': 'Nancy Fowler Arc...","[{'credit_id': '55807805c3a3685b1300060b', 'de...",1,0,0,0
1,3003,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",tt0118556,Addicted to Love,Good-natured astronomer Sam is devastated when...,8.085194,/ed6nD7h9sbojSWY2qrnDcSvDFko.jpg,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,A Comedy About Lost Loves And Last Laughs,Addicted to Love,"[{'id': 931, 'name': 'jealousy'}, {'id': 9673,...","[{'cast_id': 11, 'character': 'Maggie', 'credi...","[{'credit_id': '52fe4330c3a36847f8041367', 'de...",1,0,0,0
2,3004,6800000,"[{'id': 18, 'name': 'Drama'}, {'id': 10752, 'n...",tt1255953,Incendies,A mother's last wishes send twins Jeanne and S...,8.596012,/sEUG3qjxwHjxkzuO7plrRHhOZUH.jpg,"[{'name': 'TS Productions', 'id': 313}, {'name...","[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",...,Released,The search began at the opening of their mothe...,Incendies,"[{'id': 378, 'name': 'prison'}, {'id': 539, 'n...","[{'cast_id': 6, 'character': 'Nawal', 'credit_...","[{'credit_id': '56478092c3a36826140043af', 'de...",0,0,0,0
3,3007,0,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",tt1517177,Drei,Hanna and Simon are in a 20 year marriage with...,4.898882,/cIIQJvsZePyYYjlQJMU3J0fcinu.jpg,"[{'name': 'X-Filme Creative Pool', 'id': 1972}...","[{'iso_3166_1': 'DE', 'name': 'Germany'}]",...,Released,Imagine the possibilities.,Three,"[{'id': 572, 'name': 'sex'}, {'id': 154937, 'n...","[{'cast_id': 2, 'character': 'Hanna', 'credit_...","[{'credit_id': '52fe485bc3a36847f816358d', 'de...",0,0,0,0
4,3009,16500000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",tt0416508,Becoming Jane,A biographical portrait of a pre-fame Jane Aus...,7.829737,/iLNBdoaKzXNhZV4qbhJPkIEfLEg.jpg,"[{'name': 'Ecosse Films', 'id': 1267}, {'name'...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",...,Released,Her own life is her greatest inspiration.,Becoming Jane,"[{'id': 392, 'name': 'england'}, {'id': 934, '...","[{'cast_id': 10, 'character': 'Jane Austen', '...","[{'credit_id': '53569575c3a3687f54000051', 'de...",1,0,0,0
5,3010,90000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",tt0120363,Toy Story 2,"Andy heads off to Cowboy Camp, leaving his toy...",17.547693,/3CmK3XurcLeUyMifCR28ibzupbB.jpg,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,The toys are back!,Toy Story 2,"[{'id': 2598, 'name': 'museum'}, {'id': 3246, ...","[{'cast_id': 18, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8025073', 'de...",1,0,0,0
6,3011,2000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 27, 'n...",tt0419663,Cruel World,Millions witnessed Philip Markham's public hum...,0.262437,/uPee6Nq6IxIOnG9KYnY5kxZP2cw.jpg,"[{'name': 'Primetime Pictures', 'id': 36417}, ...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,When You Get Voted Off This Reality Show... It...,Cruel World,"[{'id': 2136, 'name': 'television'}, {'id': 30...","[{'cast_id': 1, 'character': 'Philip Markham',...","[{'credit_id': '52fe4680c3a36847f81028a9', 'de...",1,0,0,0
7,3013,5000000,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",tt0080801,The Gods Must Be Crazy,Misery is brought to a small group of Sho in t...,10.973482,/yvD2BWOEM5N4S4f6Yj8IVVjoKQO.jpg,"[{'name': 'CAT Films', 'id': 22284}, {'name': ...","[{'iso_3166_1': 'ZA', 'name': 'South Africa'},...",...,Released,The critics are raving... the natives are rest...,The Gods Must Be Crazy,"[{'id': 409, 'name': 'africa'}, {'id': 3800, '...","[{'cast_id': 5, 'character': 'Xixo', 'credit_i...","[{'credit_id': '52fe44a5c3a36847f80a1f6b', 'de...",1,0,0,0
8,3015,20000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 35, '...",tt0844286,The Brothers Bloom,The Brothers Bloom are the best con men in the...,7.973126,/xIz8iwzyjgWGzcIwHKpqhBs77ML.jpg,"[{'name': 'The Weinstein Company', 'id': 308},...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,They'd never let the truth come between them.,The Brothers Bloom,"[{'id': 3202, 'name': 'con man'}, {'id': 20313...","[{'cast_id': 1, 'character': 'Penelope Stamp',...","[{'credit_id': '52fe4426c3a368484e01239d', 'de...",1,0,0,0
9,3016,0,"[{'id': 18, 'name': 'Drama'}]",tt1533013,Beautiful Boy,A married couple on the verge of separation ar...,2.114833,/dpntGfLK58eFZLTGgwqEfwnoWBq.jpg,"[{'name': 'First Point Entertainment', 'id': 7...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,"To confront the truth, first they had to face ...",Beautiful Boy,"[{'id': 3446, 'name': 'forgiveness'}, {'id': 4...","[{'cast_id': 1, 'character': 'Bill Carroll', '...","[{'credit_id': '52fe4990c3a36847f81a0cc3', 'de...",1,0,0,0
10,3017,36000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",tt1231587,Hot Tub Time Machine,A malfunctioning time machine at a ski resort ...,11.967652,/zERxFAXiQdPAfsumIIcBFH8fOVt.jpg,"[{'name': 'United Artists', 'id': 60}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,Kick some past,Hot Tub Time Machine,"[{'id': 293, 'name': 'female nudity'}, {'id': ...","[{'cast_id': 2, 'character': 'Adam', 'credit_i...","[{'credit_id': '555adea1c3a3681089001472', 'de...",1,0,0,0
11,3018,100000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 878, '...",tt2209764,Transcendence,Two leading computer scientists work toward th...,9.730176,/4eESVBvr7KEvPGUZVL5LDWsANda.jpg,"[{'name': 'Alcon Entertainment', 'id': 1088}, ...","[{'iso_3166_1': 'CN', 'name': 'China'}, {'iso_...",...,Released,"Yesterday, Dr. Will Caster was only human...",Transcendence,"[{'id': 310, 'name': 'artificial intelligence'...","[{'cast_id': 2, 'character': 'Dr. Will Caster'...","[{'credit_id': '53fc4c480e0a267a6f00a3ac', 'de...",1,0,0,0
12,3019,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",tt0078754,All That Jazz,Bob Fosse's semi-autobiographical film celebra...,5.632325,/x4ppWRGH3pfVmEsbNC8UhvZVswd.jpg,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,All that work. All that glitter. All that pain...,All That Jazz,"[{'id': 837, 'name': 'show business'}, {'id': ...","[{'cast_id': 2, 'character': 'Joe Gideon', 'cr...","[{'credit_id': '52fe46f09251416c75088863', 'de...",1,0,0,0
13,3020,200000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",tt0120338,Titanic,"84 years later, a 101-year-old woman named Ros...",26.889070,/kHXEpyfl6zqn8a6YuozZUujufXf.jpg,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,Nothing on Earth could come between them.,Titanic,"[{'id': 2580, 'name': 'shipwreck'}, {'id': 298...","[{'cast_id': 20, 'character': 'Rose DeWitt Buk...","[{'credit_id': '52fe425ac3a36847f8017985', 'de...",1,0,0,0
14,3021,30000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",tt0124198,Very Bad Things,Kyle Fisher has one last night to celebrate li...,10.432293,/rGZ4bR7dNcAWntnVY5R8kge2IVq.jpg,"[{'name': 'Initial Entertainment Group (IEG)',...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,They've been bad. Very bad.,Very Bad Things,"[{'id': 549, 'name': 'prostitute'}, {'id': 612...","[{'cast_id': 17, 'character': 'Kyle Fisher', '...","[{'credit_id': '52fe430c9251416c75001729', 'de...",1,0,0,0
15,3022,20000000,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",tt1046163,My Best Friend's Girl,"When Dustin's girlfriend, Alexis, breaks up wi...",14.114136,/l6OAtXIo1xerbwo8xezvqr6s27Q.jpg,"[{'name': 'Lionsgate', 'id': 1632}, {'name': '...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,It's funny what love can make you do...,My Best Friend's Girl,"[{'id': 248, 'name': 'date'}, {'id': 572, 'nam...","[{'cast_id': 3, 'character': 'Tank', 'credit_i...","[{'credit_id': '52fe457f9251416c7505887d', 'de...",1,0,0,0
16,3024,27000000,"[{'id': 80, 'name': 'Crime'}, {'id': 53, 'name...",tt0324127,Suspect Zero,"A killer is on the loose, and an FBI agent sif...",7.550891,/hn5w4XwpW7RjyVUyXB39KUHxCwi.jpg,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'iso_3166_1': 'DE', 'name': 'Germany'}, {'is...",...,Released,Who's next?,Suspect Zero,"[{'id': 10714, 'name': 'serial killer'}]","[{'cast_id': 1, 'character': 'Fran Kulok', 'cr...","[{'credit_id': '52fe4492c3a36847f809daeb', 'de...",1,0,0,0
17,3026,35000000,"[{'id': 80, 'name': 'Crime'}, {'id': 53, 'name...",tt0101540,Cape Fear,Sam Bowden is a small-town corporate attorney....,10.302735,/4KvrvcqckdupXXO2YnANtyG7QLK.jpg,"[{'name': 'Universal Pictures', 'id': 33}, {'n...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,There is nothing in the dark that isn't there ...,Cape Fear,"[{'id': 378, 'name': 'prison'}, {'id': 516, 'n...","[{'cast_id': 1, 'character': 'Max Cady', 'cred...","[{'credit_id': '52fe4303c3a36847f8033dd9', 'de...",1,0,0,0
18,3027,5000000,"[{'id': 14, 'name': 'Fantasy'}, {'id': 12, 'na...",tt0093744,The New Adventures of Pippi Longstocking,After her father's ship is carried off by a su...,3.078111,/gpeTAzSW4RsxSKa4Zo2xvf9lQ9Q.jpg,"[{'name': 'Columbia Pictures', 'id': 5}]","[{'iso_3166_1': 'SE', 'name': 'Sweden'}, {'iso...",...,Released,Come see Pippi as you've never seen her before!,The New Adventures of Pippi Longstocking,"[{'id': 391, 'name': 'flying car'}, {'id': 434...","[{'cast_id': 1, 'character': 'Pippi Longstocki...","[{'credit_id': '573e27c1c3a3681d350003cc', 'de...",1,0,0,0
19,3028,44000000,"[{'id': 80, 'name': 'Crime'}, {'id': 53, 'name...",tt2140479,The Accountant,As a math savant uncooks the books for a new c...,13.465656,/afhAUuWVB7k7PjJUd4lwO3rzhSq.jpg,"[{'name': 'Zero Gravity Management', 'id': 535...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,Calculate your choices.,The Accountant,"[{'id': 1646, 'name': 'autism'}, {'id': 15009,...","[{'cast_id': 1, 'character': 'Chris Wolff', 'c...","[{'credit_id': '579dcf06c3a3683304000e0d', 'de...",1,0,0,0
20,3030,35000000,"[{'id': 28, 'name': 'Action'}, {'id': 37, 'nam...",tt0244000,American Outlaws,When a Midwest town learns that a corrupt rail...,10.855383,/cijrhkluznw3T6ZAh2wDP5EUtOs.jpg,"[{'name': 'Morgan Creek Productions', 'id': 10...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,Sometimes the wrong side of the law is the rig...,American Outlaws,"[{'id': 798, 'name': 'sheriff'}, {'id': 2673, ...","[{'cast_id': 4, 'character': 'Jesse James', 'c...","[{'credit_id': '58f7e15f9251413743000b80', 'de...",1,0,0,0
21,3031,2000000,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",tt0367027,Shortbus,A group of New Yorkers caught up in their mili...,11.547748,/iaS9XXoHW6ZVveu6wpLaTv1Bv29.jpg,"[{'name': 'Fortissimo Films', 'id': 1615}, {'n...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,Open Your Mind. And Everything Else.,Shortbus,"[{'id': 237, 'name': 'gay'}, {'id': 242, 'name...","[{'cast_id': 11, 'character': 'Sofia', 'credit...","[{'credit_id': '52fe42f1c3a36847f802ebab', 'de...",1,0,0,0
22,3032,2200000,"[{'id': 18, 'name': 'Drama'}]",tt0405508,Rang De Basanti,"A young idealistic English filmmaker, Sue, arr...",4.102052,/bAzCzOpJ6lkDDjmhnxsLbIloH9P.jpg,"[{'name': 'Flicks Motion Pictures', 'id': 2319...","[{'iso_3166_1': 'IN', 'name': 'India'}]",...,Released,A Generation Awakens,Rang De Basanti,"[{'id': 2387, 'name': 'new delhi india'}, {'id...","[{'cast_id': 2, 'character': 'DJ', 'credit_id'...","[{'credit_id': '52fe4489c3a36847f809b819', 'de...",0,0,0,0
23,3036,5500000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",tt2397535,Predestination,Predestination chronicles the life of a Tempor...,10.524204,/kDdUtDsGMQ3OYwoBtEQyJIGPz4V.jpg,"[{'name': 'Screen Australia', 'id': 7584}, {'n...","[{'iso_3166_1': 'AU', 'name': 'Australia'}]",...,Released,To save the future he must reshape the past.,Predestination,"[{'id': 4379, 'name': 'time travel'}]","[{'cast_id': 10, 'character': 'The Bartender',...","[{'credit_id': '55239feec3a3684dd4008fdd', 'de...",1,0,0,0
24,3037,18000000,"[{'id': 10749, 'name': 'Romance'}, {'id': 1040...",tt0322589,Honey,Honey Daniels (Jessica Alba) dreams of making ...,11.863954,/nC4W7JYMoqFxRBx2HR2MYDYq8Lr.jpg,"[{'name': 'Universal Pictures', 'id': 33}, {'n...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,Her dream. Her terms,Honey,"[{'id': 242, 'name': 'new york'}, {'id': 246, ...","[{'cast_id': 16, 'character': 'Honey Daniels',...","[{'credit_id': '52fe430b9251416c75001641', 'de...",1,0,0,0
25,3038,10000000,"[{'id': 27, 'name': 'Horror'}, {'id': 9648, 'n...",tt3882082,The Boy,"A nanny, working for a family whose son has ju...",17.028854,/yHhBfL2msdFWwLpjGSgPJpVmxQN.jpg,"[{'name': 'Lakeshore Entertainment', 'id': 126...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,Every child needs to feel loved.,The Boy,"[{'id': 236, 'name': 'suicide'}, {'id': 392, '...","[{'cast_id': 2, 'character': 'Greta Evans', 'c...","[{'credit_id': '57465d4ac3a36806b0000c2a', 'de...",1,0,0,0
26,3039,12516654,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",tt1816518,Ernest et Célestine,Celestine is a little mouse trying to avoid a ...,7.225779,/tSZPsJ0xETo1kUSozXWbijQDjBA.jpg,"[{'name': 'StudioCanal', 'id': 694}, {'name': ...","[{'iso_3166_1': 'BE', 'name': 'Belgium'}, {'is...",...,Released,"Bonnie and Clyde, Sid and Nancy...",Ernest & Celestine,"[{'id': 2161, 'name': 'mouse'}, {'id': 4048, '...","[{'cast_id': 5, 'character': 'La Grise (voice)...","[{'credit_id': '52fe4adbc3a368484e16accf', 'de...",0,0,0,0
27,3040,0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",tt0090315,When the Wind Blows,"With the help of government-issued pamphlets, ...",3.933121,/xRazwiqCXa3Te55ZnJGrdyIsC8X.jpg,"[{'name': 'Film Four International', 'id': 921...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",...,Released,...It's No Fairy Tale,When the Wind Blows,"[{'id': 392, 'name': 'england'}, {'id': 2217, ...","[{'cast_id': 1, 'character': 'Hilda Bloggs (vo...","[{'credit_id': '571ba7c4c3a3686524001567', 'de...",1,0,0,0
28,3041,12000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",tt1625346,Young Adult,A divorced writer from the Midwest returns to ...,6.142913,/fuYkFeGLnRkwBB95zApqI5dETQP.jpg,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,Everyone gets old. Not everyone grows up.,Young Adult,"[{'id': 931, 'name': 'jealousy'}, {'id': 10123...","[{'cast_id': 2, 'character': 'Mavis Gary', 'cr...","[{'credit_id': '55153288c3a36861950048eb', 'de...",1,0,0,0
29,3042,0,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",tt0092641,Best Seller,Hit man Cleve approaches writer/cop Dennis abo...,2.173823,/xtk9B4XdtCzQPAuQMJo14Gj5Hqr.jpg,"[{'name': 'Orion Pictures', 'id': 41}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,Writing A Book Is Easy. Writing A Best Seller ...,Best Seller,"[{'id': 242, 'name': 'new york'}, {'id': 258, ...","[{'cast_id': 10, 'character': 'Cleve', 'credit...","[{'credit_id': '52fe43d0c3a36847f8071c6f', 'de...",1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3221,7358,4000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",tt0067741,Shaft,Cool black private eye John Shaft is hired by ...,3.736880,/ez5aGeyOvG2F1QzKYHzkMmkDuM2.jpg,"[{'name': 'Metro-Goldwyn-Mayer (MGM)', 'id': 8...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,The mob wanted Harlem back. They got shaft...u...,Shaft,"[{'id': 242, 'name': 'new york'}, {'id': 577, ...","[{'cast_id': 4, 'character': 'John Shaft', 'cr...","[{'credit_id': '52fe4248c3a36847f80123b3', 'de...",1,0,0,0
3222,7359,35000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",tt1029360,Poltergeist,Legendary filmmaker Sam Raimi and director Gil...,15.968492,/fWOPN0XBvHXFYr3RsPr74qBge2I.jpg,"[{'name': 'Ghost House Pictures', 'id': 768}, ...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,They're Here. And They Know What Scares You.,Poltergeist,"[{'id': 3350, 'name': 'poltergeist'}, {'id': 3...","[{'cast_id': 2, 'character': 'Eric Bowen', 'cr...","[{'credit_id': '52fe4ee1c3a36847f82ae0b9', 'de...",1,0,0,0
3223,7360,20000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 878, 'na...",tt0095687,My Stepmother is an Alien,Trying to rescue her home planet from destruct...,6.493525,/o9feh3DGHvNZ835cm2ajYHwZwiN.jpg,"[{'name': 'Weintraub Entertainment Group', 'id...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,Man's closest encounter.,My Stepmother is an Alien,"[{'id': 9951, 'name': 'alien'}, {'id': 11931, ...","[{'cast_id': 10, 'character': 'Steven Mills', ...","[{'credit_id': '52fe44b99251416c7503ec4d', 'de...",1,0,0,0
3224,7362,55000000,"[{'id': 37, 'name': 'Western'}]",tt0381849,3:10 to Yuma,"In Arizona in the late 1800's, infamous outlaw...",18.079094,/9Nwkh0eQmkymEOR0ovAALtjSIZW.jpg,"[{'name': 'Tree Line Films', 'id': 84}, {'name...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,Time waits for one man.,3:10 to Yuma,"[{'id': 970, 'name': 'parent child relationshi...","[{'cast_id': 1, 'character': 'Ben Wade', 'cred...","[{'credit_id': '52fe43fac3a36847f807b735', 'de...",1,0,0,0
3225,7363,200000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",tt1074638,Skyfall,When Bond's latest assignment goes gravely wro...,20.309585,/9qUcmHiPpfTJTacyZyxfGTnSz0V.jpg,"[{'name': 'Columbia Pictures', 'id': 5}]","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",...,Released,Think on your sins.,Skyfall,"[{'id': 470, 'name': 'spy'}, {'id': 4289, 'nam...","[{'cast_id': 1, 'character': 'James Bond', 'cr...","[{'credit_id': '52fe46689251416c91053749', 'de...",1,0,0,0
3226,7365,27000000,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",tt0910936,Pineapple Express,A stoner and his dealer are forced to go on th...,8.461369,/scEvOPl6ZJctQVnRWHvq0pP0DkM.jpg,"[{'name': 'Columbia Pictures', 'id': 5}, {'nam...","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,Put this in your pipe and smoke it.,Pineapple Express,"[{'id': 919, 'name': 'smoking'}, {'id': 10776,...","[{'cast_id': 6, 'character': 'Dale Denton', 'c...","[{'credit_id': '564a6ba19251414dc4000c0b', 'de...",1,0,0,0
3227,7366,20000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",tt0475944,The Covenant,Four young men who belong to a supernatural le...,12.722120,/gxpTseXRrHCgL0Igm1CrKD5JQNg.jpg,"[{'name': 'Screen Gems, Inc.', 'id': 127}]","[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,Only the power of Hell can help them.,The Covenant,"[{'id': 2343, 'name': 'magic'}, {'id': 3230, '...","[{'cast_id': 23, 'character': 'Caleb Danvers',...","[{'credit_id': '52fe454fc3a36847f80c71ed', 'de...",1,0,0,0
3228,7368,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",tt0085970,Mr. Mom,Jack and Caroline are a couple making a decent...,10.693092,/8w2QCXAvz0whhlVFk0lsw01lqFK.jpg,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",...,Released,"When mom goes to work, dad goes berserk!",Mr. Mom,"[{'id': 3451, 'name': 'housewife'}, {'id': 843...","[{'cast_id': 1, 'character': 'Jack Butler', 'c...","[{'credit_id': '5985e7d792514128dc000639', 'de...",1,0,0,0

In [8]:
# genres 나누기
import ast
for i in range(len(genres_df)):
    for k in range(len(ast.literal_eval(genres_df['genres'][i]))):
        id = "genres_id_"+str(k)
        name = "genres_name_"+str(k)
        genres_df[id] = 0
        genres_df[name] = 0
#         genres_df[id].iloc[i]=ast.literal_eval(genres_df['genres'][i])[k]['id']
#         genres_df[name].iloc[i]=ast.literal_eval(genres_df['genres'][i])[k]['name']

for i in range(len(genres_df)):
    for k in range(len(ast.literal_eval(genres_df['genres'][i]))):
        id = "genres_id_"+str(k)
        name = "genres_name_"+str(k)
#         genres_df[id] = 0
#         genres_df[name] = 0
        genres_df[id].iloc[i]=ast.literal_eval(genres_df['genres'][i])[k]['id']
        genres_df[name].iloc[i]=ast.literal_eval(genres_df['genres'][i])[k]['name']
        
print("finish")

c:\users\lg\appdata\local\conda\conda\envs\python\lib\site-packages\pandas\core\indexing.py:190: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

finish

In [9]:
# production_companies 나누기
for i in range(len(production_companies_df)):
    for k in range(len(ast.literal_eval(production_companies_df['production_companies'][i]))):
        name = "company_name_"+str(k)
        id = "company_id_"+str(k)
        production_companies_df[name] = 0
        production_companies_df[id] = 0

for i in range(len(production_companies_df)):
    for k in range(len(ast.literal_eval(production_companies_df['production_companies'][i]))):
        name = "company_name_"+str(k)
        id = "company_id_"+str(k)
        production_companies_df[name].iloc[i]=ast.literal_eval(production_companies_df['production_companies'][i])[k]['name']
        production_companies_df[id].iloc[i]=ast.literal_eval(production_companies_df['production_companies'][i])[k]['id']
        
print("finish")

finish

In [10]:
# production_countries 나누기
for i in range(len(production_countries_df)):
    for k in range(len(ast.literal_eval(production_countries_df['production_countries'][i]))):
        name = "country_name_"+str(k)
        id = "country_id_"+str(k)
        production_countries_df[name] = 0
        production_countries_df[id] = 0

for i in range(len(production_countries_df)):
    for k in range(len(ast.literal_eval(production_countries_df['production_countries'][i]))):
        name = "country_name_"+str(k)
        id = "country_id_"+str(k)
        production_countries_df[name].iloc[i]=ast.literal_eval(production_countries_df['production_countries'][i])[k]['name']
        production_countries_df[id].iloc[i]=ast.literal_eval(production_countries_df['production_countries'][i])[k]['iso_3166_1']
        
print("finish")

finish

In [11]:
test_df = pd.concat([test_df, genres_df['genres_id_0']],axis=1)
test_df = pd.concat([test_df, production_companies_df['company_id_0']],axis=1)
test_df = pd.concat([test_df, production_countries_df['country_id_0']],axis=1)

In [12]:
del test_df['genres']
del test_df['original_title']
del test_df['overview']
del test_df['poster_path']
del test_df['production_companies']
del test_df['production_countries']

In [13]:
genres_id_0_dummies = pd.get_dummies(test_df['genres_id_0'])[[12,10751,16,878,28,10769,99]]

test_df = pd.concat([test_df, genres_id_0_dummies],axis=1)

del test_df['genres_id_0']

KeyError: '[10769] not in index'

In [ ]:
company_id_0_dummies = pd.get_dummies(test_df['company_id_0'])[[11,420,436,9383,521,16561,4676,89312,5295]]

test_df = pd.concat([test_df, company_id_0_dummies],axis=1)

del test_df['company_id_0']

In [ ]:
country_id_0_dummies = pd.get_dummies(test_df['country_id_0'])[['RS','PH','RO','NZ','BG','IS','CZ','UY']]

test_df = pd.concat([test_df, country_id_0_dummies],axis=1)

del test_df['country_id_0']

del test_df['imdb_id']

In [ ]:
for i in range(len(test_df)):
    if test_df['status'][i]=="Released":
        test_df['status'][i]=1
    else:
        test_df['status'][i]=0

In [ ]:
# spoken_languages_df 나누기
for i in range(len(spoken_languages_df)):
    for k in range(len(ast.literal_eval(spoken_languages_df['spoken_languages'][i]))):
        name = "spoken_languages_name_"+str(k)
        id = "spoken_languages_id_"+str(k)
        spoken_languages_df[name] = 0
        spoken_languages_df[id] = 0

for i in range(len(spoken_languages_df)):
    for k in range(len(ast.literal_eval(spoken_languages_df['spoken_languages'][i]))):
        name = "spoken_languages_name_"+str(k)
        id = "spoken_languages_id_"+str(k)
        spoken_languages_df[name].iloc[i]=ast.literal_eval(spoken_languages_df['spoken_languages'][i])[k]['name']
        spoken_languages_df[id].iloc[i]=ast.literal_eval(spoken_languages_df['spoken_languages'][i])[k]['iso_639_1']
        
print("finish")

In [ ]:
test_df = pd.concat([test_df, spoken_languages_df['spoken_languages_id_0']],axis=1)

In [ ]:
del train_prepro_data['spoken_languages']
del train_prepro_data['tagline']
del train_prepro_data['title']
del train_prepro_data['Keywords']
del train_prepro_data['cast']
del train_prepro_data['crew']

In [ ]:
country_id_0_dummies = pd.get_dummies(test_df['spoken_languages_id_0'])[['sr','tl','fa','nl','is','he','la','gd']]

In [ ]:
test_df = pd.concat([test_df, country_id_0_dummies] ,axis=1)
del test_df['spoken_languages_id_0']
del test_df['release_date']
del test_df['year']
del test_df['month']
del test_df['day']